import React, { useState } from "react";
import FaqItem from "./components/FaqItem";

export default function FAQ() {
	const [openIndex, setOpenIndex] = useState(null);

	const handleAccordionClick = (index) => {
		if (openIndex === index) {
			// Clicking on the currently open item closes it
			setOpenIndex(null);
		} else {
			// Clicking on a new item closes the currently open item and opens the clicked item
			setOpenIndex(index);
		}
	};

	const faqsList = [
		{
			question: "What is Rando and how can it benefit my projects?",
			answer:
				"Rando is a tool for generating random JSON mock data for use in various projects. It's designed to help developers, testers, and data enthusiasts quickly create realistic data sets for development, testing, and other purposes.",
		},
		{
			question:
				"Is Rando free to use, and are there any hidden costs or subscription fees?",
			answer:
				"Yes, Rando is completely free and open-source. You can use all its features without any cost. Additionally, as an open-source project, contributions from the community are welcome to improve and expand its capabilities.",
		},
		{
			question:
				"How do I customize the data generated by Rando to fit my specific needs?",
			answer:
				"You can customize the data by selecting different data types and adjusting the parameters before generating. This includes setting the number of entries, formatting options, and switching between different data providers, including Nigerian providers, to get the most relevant data for your needs.",
		},
		{
			question:
				"What types of data can I generate with Rando, and how versatile is the tool?",
			answer:
				"Rando allows you to generate various types of data, including names, addresses, emails, phone numbers, company names, and more. You can choose from a wide range of data types to suit different project requirements.",
		},
		{
			question: "Can I generate data specific to certain regions or countries?",
			answer:
				"Yes, you can generate data specific to certain regions or countries. Rando includes options for switching between different data providers, including Nigerian data sources, allowing you to create contextually accurate datasets.",
		},

		{
			question:
				"How secure is the data generated by Rando, and does it pose any privacy risks?",
			answer:
				"The data generated by Rando is purely synthetic and not based on real personal information. This ensures that the data is secure and safe to use for testing and development purposes without any privacy concerns. You can use Rando's data with confidence, knowing that it doesn't contain any sensitive or private information.",
		},
		{
			question: "Can I use Rando's generated data for commercial projects?",
			answer:
				"Yes, you can use Rando's generated data for commercial projects. The data is free to use and integrate into any project, whether for personal or commercial purposes.",
		},
	];
	return (
		<section className="py-[100px] h-fit bg-black-2 text-white-1 text-sm md:text-base lg:text-base xl:text-lg px-[20px] md:px-[50px] lg:px-[90px] xl:px-[120px]">
			<div className="text-center flex flex-col gap-4 items-center">
				<p className="font-light">
					Create, customize, and download mock data for your projects with ease.
				</p>
				<h1 className="text-3xl md:text-4xl lg:text-5xl font-medium tracking-[-1.2px]">
					Frequently Asked Questions
				</h1>
			</div>

			<div className="mt-[64px] w-full lg:w-[75%] mx-auto max-w-[1240px] lg:min-w-[970px]">
				<div className="flex flex-col gap-0">
					{faqsList.map((faq, index) => (
						<FaqItem
							key={index}
							question={faq.question}
							answer={faq.answer}
							isOpen={index === openIndex}
							onAccordionClick={() => handleAccordionClick(index)}
						/>
					))}
				</div>
				<hr className="border-white-2/30" />
			</div>
		</section>
	);
}
